apiVersion: apps/v1
kind: Deployment
metadata:
  name: software-construction-app
  labels:
    app: software-construction-app
spec:
  replicas: 1 # Reduced for local testing
  selector:
    matchLabels:
      app: software-construction-app
  template:
    metadata:
      labels:
        app: software-construction-app
    spec:
      containers:
        - name: software-construction-app
          image: moath070/software-construction-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-env-secret
          resources:
            requests:
              memory: "128Mi" # Reduced for local
              cpu: "100m"
            limits:
              memory: "256Mi" # Reduced for local
              cpu: "200m"
